### ISSUE TITLE
Choose a language for Back-end

### ISSUE THREAD

**Issue by julwrites** [chillianproject/Mawie-Backend#1]
Backend language, which should be well-documented, and well-supported on any major platform. 

Possible candidates:
- Golang
- C#
- NodeJS
- Clojure
- Ruby
- Python
- Rust

**Comment by julwrites** [comment]
Considering that we have more freedom on the backend (since we are not limited by framework), we might want to choose the language to learn here.

**Comment by ChinkyMoralde** [comment]
Decided to use RUST for backend development.
